# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.81.0
  hooks:
    - id: terraform_docs
      exclude: ^\.github/.*$|^\.circleci/.*$|^\.terraform/.*$|^\.terragrunt_cache/.*$|^var[s]/.*.tfvar[s]$|^modules/.*$
      args:
        - --args=--lockfile=false
        - --args=--config=./.terraform-docs.yml
