name: Code Scanning
permissions:
  actions: read
  checks: read
  contents: read
  deployments: read
  id-token: write
  issues: write
  discussions: write
  packages: none
  pages: none
  pull-requests: write
  repository-projects: read
  security-events: write
  statuses: write
on:
  push:
    branches:
      - master
      - main
      - feat/*
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    name: Code Scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
